name: OpenAPI - Lint

on:
  push:
    paths:
      - 'redocly.yaml'
      - 'src/docs/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm install
      - run: npm run lint
